from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
import joblib

# Bước 1: Dữ liệu
data = [
    # -------- FAN --------
    ("bật quạt số 1", ("1", "button-fan")),
    ("bật quạt số 1", ("1", "button-fan")),
    ("bật quạt số 1", ("1", "button-fan")),
    ("bật quạt số 1", ("1", "button-fan")),
    ("bật quạt số 1.", ("1", "button-fan")),
    ("bật quạt số 1.", ("1", "button-fan")),
    ("bật quạt số 1.", ("1", "button-fan")),
    ("bật quạt số 1.", ("1", "button-fan")),
    ("bật quạt số một.", ("1", "button-fan")),
    ("bật quạt số một.", ("1", "button-fan")),
    ("bật quạt số một.", ("1", "button-fan")),
    ("bật quạt số một.", ("1", "button-fan")),
    ("bật quạt số một.", ("1", "button-fan")),
    ("bật quạt số một.", ("1", "button-fan")),
    ("bật quạt số một.", ("1", "button-fan")),
    ("bật quạt số một.", ("1", "button-fan")),
    ("bật quạt số một.", ("1", "button-fan")),
    ("bật quạt số một.", ("1", "button-fan")),
    ("bật quạt số một.", ("1", "button-fan")),
    ("bật quạt số một.", ("1", "button-fan")),
    ("bật quạt số một.", ("1", "button-fan")),
    ("bật quạt số một.", ("1", "button-fan")),
    ("bật quạt số 2", ("2", "button-fan")),
    ("bật quạt số 2", ("2", "button-fan")),
    ("bật quạt số 2.", ("2", "button-fan")),
    ("bật quạt số 2.", ("2", "button-fan")),
    ("bật quạt số 2.", ("2", "button-fan")),
    ("bật quạt số 2.", ("2", "button-fan")),
    ("bật quạt số 2.", ("2", "button-fan")),
    ("bật quạt số hai.", ("2", "button-fan")),
    ("bật quạt số hai.", ("2", "button-fan")),
    ("bật quạt số hai.", ("2", "button-fan")),
    ("bật quạt số hai.", ("2", "button-fan")),
    ("bật quạt số hai.", ("2", "button-fan")),
    ("bật quạt số hai.", ("2", "button-fan")),
    ("bật quạt số hai.", ("2", "button-fan")),
    ("bật quạt số hai.", ("2", "button-fan")),
    ("bật quạt số hai.", ("2", "button-fan")),
    ("bật quạt số hai.", ("2", "button-fan")),
    ("bật quạt số 3", ("3", "button-fan")),
    ("bật quạt số 3", ("3", "button-fan")),
    ("bật quạt số 3", ("3", "button-fan")),
    ("bật quạt số 3", ("3", "button-fan")),
    ("Bật quạt số 3.", ("3", "button-fan")),
    ("Bật quạt số 3.", ("3", "button-fan")),
    ("Bật quạt số 3.", ("3", "button-fan")),
    ("Bật quạt số 3.", ("3", "button-fan")),
    ("Bật quạt số ba.", ("3", "button-fan")),
    ("Bật quạt số ba.", ("3", "button-fan")),
    ("Bật quạt số ba.", ("3", "button-fan")),
    ("Bật quạt số ba.", ("3", "button-fan")),
    ("Bật quạt số ba.", ("3", "button-fan")),
    ("Bật quạt số ba.", ("3", "button-fan")),
    ("Bật quạt số ba.", ("3", "button-fan")),
    ("Bật quạt số ba.", ("3", "button-fan")),
    ("Bật quạt số ba.", ("3", "button-fan")),
    ("Bật quạt số ba.", ("3", "button-fan")),
    ("Bật quạt số ba.", ("3", "button-fan")),
    ("Bật quạt số ba.", ("3", "button-fan")),
    ("Bật quạt số 4", ("4", "button-fan")),
    ("Bật quạt số 4", ("4", "button-fan")),
    ("Bật quạt số 4", ("4", "button-fan")),
    ("Bật quạt số 4", ("4", "button-fan")),
    ("Bật quạt số 4.", ("4", "button-fan")),
    ("Bật quạt số 4.", ("4", "button-fan")),
    ("Bật quạt số 4.", ("4", "button-fan")),
    ("Bật quạt số 4.", ("4", "button-fan")),
    ("Bật quạt số 4.", ("4", "button-fan")),
    ("Bật quạt số bốn.", ("4", "button-fan")),
    ("Bật quạt số bốn.", ("4", "button-fan")),
    ("Bật quạt số bốn.", ("4", "button-fan")),
    ("Bật quạt số bốn.", ("4", "button-fan")),
    ("Bật quạt số bốn.", ("4", "button-fan")),
    ("Bật quạt số bốn.", ("4", "button-fan")),
    ("Bật quạt số bốn.", ("4", "button-fan")),
    ("Bật quạt số bốn.", ("4", "button-fan")),
    ("Bật quạt số bốn.", ("4", "button-fan")),
    ("Bật quạt số bốn.", ("4", "button-fan")),
    ("Bật quạt số bốn.", ("4", "button-fan")),
    ("Bật quạt số bốn.", ("4", "button-fan")),
    ("quạt số 1.", ("1", "button-fan")),
    ("quạt số 1.", ("1", "button-fan")),
    ("quạt số 1.", ("1", "button-fan")),
    ("quạt số 1.", ("1", "button-fan")),
    ("quạt số 1.", ("1", "button-fan")),
    ("quạt số 1.", ("1", "button-fan")),
    ("quạt số 1.", ("1", "button-fan")),
    ("quạt số một.", ("1", "button-fan")),
    ("quạt số một.", ("1", "button-fan")),
    ("quạt số một.", ("1", "button-fan")),
    ("quạt số một.", ("1", "button-fan")),
    ("quạt số một.", ("1", "button-fan")),
    ("quạt số một.", ("1", "button-fan")),
    ("quạt số một.", ("1", "button-fan")),
    ("quạt số một.", ("1", "button-fan")),
    ("quạt số một.", ("1", "button-fan")),
    ("quạt số 2.", ("2", "button-fan")),
    ("quạt số 2.", ("2", "button-fan")),
    ("quạt số 2.", ("2", "button-fan")),
    ("quạt số 2.", ("2", "button-fan")),
    ("quạt số 2.", ("2", "button-fan")),
    ("quạt số 2.", ("2", "button-fan")),
    ("quạt số 2.", ("2", "button-fan")),
    ("quạt số hai.", ("2", "button-fan")),
    ("quạt số hai.", ("2", "button-fan")),
    ("quạt số hai.", ("2", "button-fan")),
    ("quạt số hai.", ("2", "button-fan")),
    ("quạt số hai.", ("2", "button-fan")),
    ("quạt số hai.", ("2", "button-fan")),
    ("quạt số hai.", ("2", "button-fan")),
    ("quạt số hai.", ("2", "button-fan")),
    ("quạt số 3.", ("3", "button-fan")),
    ("quạt số 3.", ("3", "button-fan")),
    ("quạt số 3.", ("3", "button-fan")),
    ("quạt số 3.", ("3", "button-fan")),
    ("quạt số 3.", ("3", "button-fan")),
    ("quạt số 3.", ("3", "button-fan")),
    ("quạt số 3.", ("3", "button-fan")),
    ("quạt số 3.", ("3", "button-fan")),
    ("quạt số 3.", ("3", "button-fan")),
    ("quạt số ba.", ("3", "button-fan")),
    ("quạt số ba.", ("3", "button-fan")),
    ("quạt số ba.", ("3", "button-fan")),
    ("quạt số ba.", ("3", "button-fan")),
    ("quạt số ba.", ("3", "button-fan")),
    ("quạt số ba.", ("3", "button-fan")),
    ("quạt số ba.", ("3", "button-fan")),
    ("quạt số ba.", ("3", "button-fan")),
    ("quạt số ba.", ("3", "button-fan")),
    ("quạt số 4.", ("4", "button-fan")),
    ("quạt số 4.", ("4", "button-fan")),
    ("quạt số 4.", ("4", "button-fan")),
    ("quạt số 4.", ("4", "button-fan")),
    ("quạt số 4.", ("4", "button-fan")),
    ("quạt số 4.", ("4", "button-fan")),
    ("quạt số 4.", ("4", "button-fan")),
    ("quạt số 4.", ("4", "button-fan")),
    ("quạt số 4.", ("4", "button-fan")),
    ("quạt số 4.", ("4", "button-fan")),
    ("quạt số 4.", ("4", "button-fan")),
    ("quạt số 4.", ("4", "button-fan")),
    ("quạt số bốn.", ("4", "button-fan")),
    ("quạt số bốn.", ("4", "button-fan")),
    ("quạt số bốn.", ("4", "button-fan")),
    ("quạt số bốn.", ("4", "button-fan")),
    ("quạt số bốn.", ("4", "button-fan")),
    ("quạt số bốn.", ("4", "button-fan")),
    ("quạt số bốn.", ("4", "button-fan")),
    ("quạt số bốn.", ("4", "button-fan")),
    ("quạt số bốn.", ("4", "button-fan")),
    ("quạt số bốn.", ("4", "button-fan")),
    ("quạt số bốn.", ("4", "button-fan")),
    ("ngưng quat", ("0", "button-fan")),
    ("ngưng quat", ("0", "button-fan")),
    ("ngưng quat", ("0", "button-fan")),
    ("ngưng quat", ("0", "button-fan")),
    ("ngưng quat", ("0", "button-fan")),
    ("ngưng quat", ("0", "button-fan")),
    ("ngưng quat", ("0", "button-fan")),
    ("ngưng quat", ("0", "button-fan")),
    ("ngưng quat", ("0", "button-fan")),
    ("ngưng quat", ("0", "button-fan")),
    ("chạy quạt số 1.", ("1", "button-fan")),
    ("chạy quạt số 1.", ("1", "button-fan")),
    ("chạy quạt số 1.", ("1", "button-fan")),
    ("chạy quạt số 1.", ("1", "button-fan")),
    ("chạy quạt số 1.", ("1", "button-fan")),
    ("chạy quạt số một.", ("1", "button-fan")),
    ("chạy quạt số một.", ("1", "button-fan")),
    ("chạy quạt số một.", ("1", "button-fan")),
    ("chạy quạt số một.", ("1", "button-fan")),
    ("chạy quạt số một.", ("1", "button-fan")),
    ("chạy quạt số một.", ("1", "button-fan")),
    ("chạy quạt số một.", ("1", "button-fan")),
    ("chạy quạt số một.", ("1", "button-fan")),
    ("chạy quạt số 2.", ("2", "button-fan")),
    ("chạy quạt số 2.", ("2", "button-fan")),
    ("chạy quạt số 2.", ("2", "button-fan")),
    ("chạy quạt số 2.", ("2", "button-fan")),
    ("chạy quạt số 2.", ("2", "button-fan")),
    ("chạy quạt số 2.", ("2", "button-fan")),
    ("chạy quạt số hai.", ("2", "button-fan")),
    ("chạy quạt số hai.", ("2", "button-fan")),
    ("chạy quạt số hai.", ("2", "button-fan")),
    ("chạy quạt số hai.", ("2", "button-fan")),
    ("chạy quạt số hai.", ("2", "button-fan")),
    ("chạy quạt số hai.", ("2", "button-fan")),
    ("chạy quạt số hai.", ("2", "button-fan")),
    ("chạy quạt số hai.", ("2", "button-fan")),
    ("chạy quạt số hai.", ("2", "button-fan")),
    ("chạy quạt số 3.", ("3", "button-fan")),
    ("chạy quạt số 3.", ("3", "button-fan")),
    ("chạy quạt số 3.", ("3", "button-fan")),
    ("chạy quạt số 3.", ("3", "button-fan")),
    ("chạy quạt số 3.", ("3", "button-fan")),
    ("chạy quạt số ba.", ("3", "button-fan")),
    ("chạy quạt số ba.", ("3", "button-fan")),
    ("chạy quạt số ba.", ("3", "button-fan")),
    ("chạy quạt số ba.", ("3", "button-fan")),
    ("chạy quạt số ba.", ("3", "button-fan")),
    ("chạy quạt số ba.", ("3", "button-fan")),
    ("chạy quạt số ba.", ("3", "button-fan")),
    ("chạy quạt số ba.", ("3", "button-fan")),
    ("chạy quạt số 4.", ("4", "button-fan")),
    ("chạy quạt số 4.", ("4", "button-fan")),
    ("chạy quạt số 4.", ("4", "button-fan")),
    ("chạy quạt số 4.", ("4", "button-fan")),
    ("chạy quạt số 4.", ("4", "button-fan")),
    ("chạy quạt số 4.", ("4", "button-fan")),
    ("chạy quạt số bốn.", ("4", "button-fan")),
    ("chạy quạt số bốn.", ("4", "button-fan")),
    ("chạy quạt số bốn.", ("4", "button-fan")),
    ("chạy quạt số bốn.", ("4", "button-fan")),
    ("chạy quạt số bốn.", ("4", "button-fan")),
    ("chạy quạt số bốn.", ("4", "button-fan")),
    ("chạy quạt số bốn.", ("4", "button-fan")),
    ("chạy quạt số bốn.", ("4", "button-fan")),
    ("chạy quạt số bốn.", ("4", "button-fan")),
    ("tắt quạt", ("0", "button-fan")),
    ("tắt quạt", ("0", "button-fan")),
    ("tắt quạt", ("0", "button-fan")),
    ("tắt quạt", ("0", "button-fan")),
    ("tắt quạt", ("0", "button-fan")),
    ("tắt quạt", ("0", "button-fan")),
    ("tắt quạt", ("0", "button-fan")),
    ("mở quạt.", ("1", "button-fan")),
    ("mở quạt.", ("1", "button-fan")),
    ("mở quạt.", ("1", "button-fan")),
    ("mở quạt.", ("1", "button-fan")),
    ("mở quạt.", ("1", "button-fan")),
    ("mở quạt số 1.", ("1", "button-fan")),
    ("mở quạt số 1.", ("1", "button-fan")),
    ("mở quạt số 1.", ("1", "button-fan")),
    ("mở quạt số 1.", ("1", "button-fan")),
    ("mở quạt số 1.", ("1", "button-fan")),
    ("mở quạt số 1.", ("1", "button-fan")),
    ("mở quạt số 1.", ("1", "button-fan")),
    ("mở quạt số một.", ("1", "button-fan")),
    ("mở quạt số một.", ("1", "button-fan")),
    ("mở quạt số một.", ("1", "button-fan")),
    ("mở quạt số một.", ("1", "button-fan")),
    ("mở quạt số một.", ("1", "button-fan")),
    ("mở quạt số một.", ("1", "button-fan")),
    ("mở quạt số một.", ("1", "button-fan")),
    ("mở quạt số 2.", ("2", "button-fan")),
    ("mở quạt số 2.", ("2", "button-fan")),
    ("mở quạt số 2.", ("2", "button-fan")),
    ("mở quạt số 2.", ("2", "button-fan")),
    ("mở quạt số 2.", ("2", "button-fan")),
    ("mở quạt số 2.", ("2", "button-fan")),
    ("mở quạt số 2.", ("2", "button-fan")),
    ("mở quạt số 2.", ("2", "button-fan")),
    ("mở quạt số 2.", ("2", "button-fan")),
    ("mở quạt số hai.", ("2", "button-fan")),
    ("mở quạt số hai.", ("2", "button-fan")),
    ("mở quạt số hai.", ("2", "button-fan")),
    ("mở quạt số hai.", ("2", "button-fan")),
    ("mở quạt số hai.", ("2", "button-fan")),
    ("mở quạt số hai.", ("2", "button-fan")),
    ("mở quạt số hai.", ("2", "button-fan")),
    ("mở quạt số hai.", ("2", "button-fan")),
    ("mở quạt số hai.", ("2", "button-fan")),
    ("mở quạt số 3.", ("3", "button-fan")),
    ("mở quạt số 3.", ("3", "button-fan")),
    ("mở quạt số 3.", ("3", "button-fan")),
    ("mở quạt số 3.", ("3", "button-fan")),
    ("mở quạt số 3.", ("3", "button-fan")),
    ("mở quạt số 3.", ("3", "button-fan")),
    ("mở quạt số 3.", ("3", "button-fan")),
    ("mở quạt số 3.", ("3", "button-fan")),
    ("mở quạt số 3.", ("3", "button-fan")),
    ("mở quạt số ba.", ("3", "button-fan")),
    ("mở quạt số ba.", ("3", "button-fan")),
    ("mở quạt số ba.", ("3", "button-fan")),
    ("mở quạt số ba.", ("3", "button-fan")),
    ("mở quạt số ba.", ("3", "button-fan")),
    ("mở quạt số ba.", ("3", "button-fan")),
    ("mở quạt số ba.", ("3", "button-fan")),
    ("mở quạt số ba.", ("3", "button-fan")),
    ("mở quạt số 4.", ("4", "button-fan")),
    ("mở quạt số 4.", ("4", "button-fan")),
    ("mở quạt số 4.", ("4", "button-fan")),
    ("mở quạt số 4.", ("4", "button-fan")),
    ("mở quạt số 4.", ("4", "button-fan")),
    ("mở quạt số 4.", ("4", "button-fan")),
    ("mở quạt số 4.", ("4", "button-fan")),
    ("mở quạt số bốn.", ("4", "button-fan")),
    ("mở quạt số bốn.", ("4", "button-fan")),
    ("mở quạt số bốn.", ("4", "button-fan")),
    ("mở quạt số bốn.", ("4", "button-fan")),
    ("mở quạt số bốn.", ("4", "button-fan")),
    ("mở quạt số bốn.", ("4", "button-fan")),
    ("mở quạt số bốn.", ("4", "button-fan")),
    ("mở quạt số bốn.", ("4", "button-fan")),
    ("đóng quạt", ("0", "button-fan")),
    ("đóng quạt", ("0", "button-fan")),
    ("đóng quạt", ("0", "button-fan")),
    ("trời nóng quá, bật quạt lên", ("3", "button-fan")),
    ("trời lạnh quá, bật quạt lên", ("3", "button-fan")),
    ("trời nóng quá, bật số 3 đi", ("3", "button-fan")),
    ("trời nóng quá, bật số 2 đi", ("2", "button-fan")),
    ("trời nóng quá, bật số 1 đi", ("1", "button-fan")),
    ("cho quạt chạy đi", ("1", "button-fan")),
    ("làm ơn bật quạt", ("1", "button-fan")),
    ("quạt lên!", ("1", "button-fan")),
    ("quạt lên!", ("1", "button-fan")),
    ("quạt lên!", ("1", "button-fan")),
    ("ngừng quạt", ("0", "button-fan")),
    ("ngừng quạt", ("0", "button-fan")),
    ("ngừng quạt", ("0", "button-fan")),
    ("ngừng quạt", ("0", "button-fan")),
    ("ngừng quạt", ("0", "button-fan")),
    ("tắt cái quạt đó đi", ("0", "button-fan")),
    ("tắt cái quạt đó đi", ("0", "button-fan")),
    ("cho quạt ngừng chạy", ("0", "button-fan")),
    ("cho quạt ngừng chạy", ("0", "button-fan")),
    ("quạt off", ("0", "button-fan")),
    ("quạt off", ("0", "button-fan")),
    ("quạt off", ("0", "button-fan")),
    ("quạt off", ("0", "button-fan")),
    ("quạt on", ("1", "button-fan")),
    ("quạt on", ("1", "button-fan")),
    ("rút điện quạt", ("0", "button-fan")),
    ("cắm điện quạt", ("1", "button-fan")),
    ("điều khiển cho quạt chạy", ("1", "button-fan")),
    ("điều khiển cho quạt chạy", ("1", "button-fan")),
    ("điều khiển cho quạt chạy", ("1", "button-fan")),
    ("điều khiển cho quạt chạy", ("1", "button-fan")),
    ("điều khiển cho quạt tắt", ("0", "button-fan")),
    ("bật quạt", ("1", "button-fan")),
    ("bật quạt", ("1", "button-fan")),
    ("bật quạt", ("1", "button-fan")),
    ("bật quạt", ("1", "button-fan")),

    ("fan on", ("3", "button-fan")),
    ("fan on", ("3", "button-fan")),
    ("fan on", ("3", "button-fan")),
    ("fan on", ("3", "button-fan")),
    ("fan on", ("3", "button-fan")),
    ("fan on", ("3", "button-fan")),
    ("fan on", ("3", "button-fan")),
    ("fan on", ("3", "button-fan")),
    ("fan off", ("0", "button-fan")),
    ("fan off", ("0", "button-fan")),
    ("fan off", ("0", "button-fan")),
    ("fan off", ("0", "button-fan")),
    ("fan off", ("0", "button-fan")),
    ("fan off", ("0", "button-fan")),
    ("fan off", ("0", "button-fan")),
    ("fan off", ("0", "button-fan")),
    ("fan off", ("0", "button-fan")),
    ("turn on the fan", ("1", "button-fan")),
    ("turn on the fan", ("1", "button-fan")),
    ("turn on the fan", ("1", "button-fan")),
    ("turn on the fan", ("1", "button-fan")),
    ("turn on the fan", ("1", "button-fan")),
    ("turn on the fan", ("1", "button-fan")),
    ("turn on the fan", ("1", "button-fan")),
    ("turn on the fan", ("1", "button-fan")),
    ("turn on the fan", ("1", "button-fan")),
    ("turn on the fan", ("1", "button-fan")),
    ("turn on fan number 1", ("1", "button-fan")),
    ("turn on fan number 1", ("1", "button-fan")),
    ("turn on fan number 1", ("1", "button-fan")),
    ("turn on fan number 1", ("1", "button-fan")),
    ("turn on fan number 1.", ("1", "button-fan")),
    ("turn on fan number 1.", ("1", "button-fan")),
    ("turn on fan number 1.", ("1", "button-fan")),
    ("turn on fan number one.", ("1", "button-fan")),
    ("turn on fan number one.", ("1", "button-fan")),
    ("turn on fan number one.", ("1", "button-fan")),
    ("turn on fan number one.", ("1", "button-fan")),
    ("turn on fan number one.", ("1", "button-fan")),
    ("turn on fan number one.", ("1", "button-fan")),
    ("turn on fan number one.", ("1", "button-fan")),
    ("turn on fan number 2.", ("2", "button-fan")),
    ("turn on fan number 2.", ("2", "button-fan")),
    ("turn on fan number 2.", ("2", "button-fan")),
    ("turn on fan number 2.", ("2", "button-fan")),
    ("turn on fan number 2.", ("2", "button-fan")),
    ("turn on fan number 2.", ("2", "button-fan")),
    ("turn on fan number 2.", ("2", "button-fan")),
    ("turn on fan number two.", ("2", "button-fan")),
    ("turn on fan number two.", ("2", "button-fan")),
    ("turn on fan number two.", ("2", "button-fan")),
    ("turn on fan number two.", ("2", "button-fan")),
    ("turn on fan number two.", ("2", "button-fan")),
    ("turn on fan number two.", ("2", "button-fan")),
    ("turn on fan number two.", ("2", "button-fan")),
    ("turn on fan number two.", ("2", "button-fan")),
    ("turn on fan number two.", ("2", "button-fan")),
    ("turn on fan number 3.", ("3", "button-fan")),
    ("turn on fan number 3.", ("3", "button-fan")),
    ("turn on fan number 3.", ("3", "button-fan")),
    ("turn on fan number 3.", ("3", "button-fan")),
    ("turn on fan number 3.", ("3", "button-fan")),
    ("turn on fan number 3.", ("3", "button-fan")),
    ("turn on fan number three.", ("3", "button-fan")),
    ("turn on fan number three.", ("3", "button-fan")),
    ("turn on fan number three.", ("3", "button-fan")),
    ("turn on fan number three.", ("3", "button-fan")),
    ("turn on fan number three.", ("3", "button-fan")),
    ("turn on fan number three.", ("3", "button-fan")),
    ("turn on fan number three.", ("3", "button-fan")),
    ("turn on fan number 4.", ("4", "button-fan")),
    ("turn on fan number 4.", ("4", "button-fan")),
    ("turn on fan number 4.", ("4", "button-fan")),
    ("turn on fan number 4.", ("4", "button-fan")),
    ("turn on fan number 4.", ("4", "button-fan")),
    ("turn on fan number 4.", ("4", "button-fan")),
    ("turn on fan number 4.", ("4", "button-fan")),
    ("turn on fan number four.", ("4", "button-fan")),
    ("turn on fan number four.", ("4", "button-fan")),
    ("turn on fan number four.", ("4", "button-fan")),
    ("turn on fan number four.", ("4", "button-fan")),
    ("turn on fan number four.", ("4", "button-fan")),
    ("turn on fan number four.", ("4", "button-fan")),
    ("turn on fan number four.", ("4", "button-fan")),
    ("switch the fan on", ("1", "button-fan")),
    ("switch the fan on", ("1", "button-fan")),
    ("please turn on the fan", ("1", "button-fan")),
    ("please turn on the fan", ("1", "button-fan")),
    ("please turn on the fan", ("1", "button-fan")),
    ("please turn on the fan", ("1", "button-fan")),
    ("please turn on the fan", ("1", "button-fan")),
    ("please turn on the fan", ("1", "button-fan")),
    ("turn off the fan.", ("0", "button-fan")),
    ("turn off the fan.", ("0", "button-fan")),
    ("turn off the fan.", ("0", "button-fan")),
    ("turn off the fan.", ("0", "button-fan")),
    ("turn off the fan.", ("0", "button-fan")),
    ("turn off the fan.", ("0", "button-fan")),
    ("turn off the fan.", ("0", "button-fan")),
    ("turn off the fan.", ("0", "button-fan")),
    ("turn off the fan.", ("0", "button-fan")),
    ("turn off the fan.", ("0", "button-fan")),
    ("turn off the fan.", ("0", "button-fan")),
    ("turn off the fan.", ("0", "button-fan")),
    ("switch off fan.", ("0", "button-fan")),
    ("switch off fan.", ("0", "button-fan")),
    ("switch off fan.", ("0", "button-fan")),
    ("switch off fan.", ("0", "button-fan")),
    ("switch off fan.", ("0", "button-fan")),
    ("switch off fan.", ("0", "button-fan")),
    ("switch off fan.", ("0", "button-fan")),
    ("switch off fan.", ("0", "button-fan")),

    # -------- LIGHT / LED --------
    ("Đèn đâu", ("ON", "button-led")),
    ("Đèn đâu", ("ON", "button-led")),
    ("Đèn đâu", ("ON", "button-led")),
    ("Đèn đâu", ("ON", "button-led")),
    ("bật đèn", ("ON", "button-led")),
    ("bật đèn", ("ON", "button-led")),
    ("bật đèn", ("ON", "button-led")),
    ("bật đèn", ("ON", "button-led")),
    ("bật đèn", ("ON", "button-led")),
    ("bật đèn", ("ON", "button-led")),
    ("bật đèn", ("ON", "button-led")),
    ("bật đèn", ("ON", "button-led")),
    ("bật đèn", ("ON", "button-led")),
    ("bật đèn", ("ON", "button-led")),
    ("bật đèn", ("ON", "button-led")),
    ("bật đèn", ("ON", "button-led")),
    ("bật đèn", ("ON", "button-led")),
    ("bật đèn", ("ON", "button-led")),
    ("bật đèn", ("ON", "button-led")),
    ("tắt đèn", ("OFF", "button-led")),
    ("tắt đèn", ("OFF", "button-led")),
    ("tắt đèn", ("OFF", "button-led")),
    ("tắt đèn", ("OFF", "button-led")),
    ("tắt đèn", ("OFF", "button-led")),
    ("tắt đèn", ("OFF", "button-led")),
    ("tắt đèn", ("OFF", "button-led")),
    ("tắt đèn", ("OFF", "button-led")),
    ("tắt đèn", ("OFF", "button-led")),
    ("tắt đèn", ("OFF", "button-led")),
    ("tắt đèn", ("OFF", "button-led")),
    ("tắt đèn", ("OFF", "button-led")),
    ("tắt đèn", ("OFF", "button-led")),
    ("tắt đèn", ("OFF", "button-led")),
    ("tắt đèn", ("OFF", "button-led")),
    ("tắt đèn", ("OFF", "button-led")),
    ("tắt đèn", ("OFF", "button-led")),
    ("tắt đèn", ("OFF", "button-led")),
    ("bật bóng điện", ("ON", "button-led")),
    ("tắt bóng điện", ("OFF", "button-led")),
    ("bật điện lên", ("ON", "button-led")),
    ("tắt điện đi", ("OFF", "button-led")),
    ("mở đèn", ("ON", "button-led")),
    ("mở đèn", ("ON", "button-led")),
    ("mở đèn", ("ON", "button-led")),
    ("mở đèn", ("ON", "button-led")),
    ("mở đèn", ("ON", "button-led")),
    ("mở đèn", ("ON", "button-led")),
    ("mở đèn", ("ON", "button-led")),
    ("mở đèn", ("ON", "button-led")),
    ("đóng đèn", ("OFF", "button-led")),
    ("đóng đèn", ("OFF", "button-led")),
    ("đóng đèn", ("OFF", "button-led")),
    ("đóng đèn", ("OFF", "button-led")),
    ("đóng đèn", ("OFF", "button-led")),
    ("đóng đèn", ("OFF", "button-led")),
    ("đóng đèn", ("OFF", "button-led")),
    ("đóng đèn", ("OFF", "button-led")),
    ("đóng đèn", ("OFF", "button-led")),
    ("đóng đèn", ("OFF", "button-led")),
    ("ngắt đèn", ("OFF", "button-led")),
    ("ngắt đèn", ("OFF", "button-led")),
    ("ngắt đèn", ("OFF", "button-led")),
    ("ngắt đèn", ("OFF", "button-led")),
    ("ngắt đèn", ("OFF", "button-led")),
    ("ngắt đèn", ("OFF", "button-led")),
    ("ngắt đèn", ("OFF", "button-led")),
    ("ngắt đèn", ("OFF", "button-led")),
    ("ngắt đèn", ("OFF", "button-led")),
    ("bật cái đèn kia", ("ON", "button-led")),
    ("bật cái đèn kia", ("ON", "button-led")),
    ("bật cái đèn kia", ("ON", "button-led")),
    ("bật cái đèn kia", ("ON", "button-led")),
    ("bật cái đèn kia", ("ON", "button-led")),
    ("bật cái đèn kia", ("ON", "button-led")),
    ("tối quá, bật đèn đi", ("ON", "button-led")),
    ("cho đèn sáng lên", ("ON", "button-led")),
    ("sáng lên!", ("ON", "button-led")),
    ("sáng lên!", ("ON", "button-led")),
    ("sáng lên!", ("ON", "button-led")),
    ("sáng lên!", ("ON", "button-led")),
    ("sáng lên!", ("ON", "button-led")),
    ("sáng lên!", ("ON", "button-led")),
    ("sáng lên!", ("ON", "button-led")),
    ("sáng lên!", ("ON", "button-led")),
    ("sáng lên!", ("ON", "button-led")),
    ("sáng lên!", ("ON", "button-led")),
    ("tắt cái đèn đó", ("OFF", "button-led")),
    ("đèn tắt đi", ("OFF", "button-led")),

    ("Lumos", ("ON", "button-led")),
    ("Nox", ("ON", "button-led")),
    ("turn on led", ("ON", "button-led")),
    ("turn on led", ("ON", "button-led")),
    ("turn on led", ("ON", "button-led")),
    ("turn on led", ("ON", "button-led")),
    ("turn on led", ("ON", "button-led")),
    ("turn on led", ("ON", "button-led")),
    ("turn on led", ("ON", "button-led")),
    ("turn on led", ("ON", "button-led")),
    ("turn on led", ("ON", "button-led")),
    ("turn on led", ("ON", "button-led")),
    ("turn on led", ("ON", "button-led")),
    ("turn on led", ("ON", "button-led")),
    ("turn on led", ("ON", "button-led")),
    ("turn on led", ("ON", "button-led")),
    ("turn on led", ("ON", "button-led")),
    ("turn on led", ("ON", "button-led")),
    ("turn on led", ("ON", "button-led")),
    ("turn on the light", ("ON", "button-led")),
    ("turn on the light", ("ON", "button-led")),
    ("turn on the light", ("ON", "button-led")),
    ("turn on the light", ("ON", "button-led")),
    ("turn on the light", ("ON", "button-led")),
    ("turn on the light", ("ON", "button-led")),
    ("turn on the light", ("ON", "button-led")),
    ("turn on the light", ("ON", "button-led")),
    ("turn on the light", ("ON", "button-led")),
    ("turn on the light", ("ON", "button-led")),
    ("turn on the light", ("ON", "button-led")),
    ("turn on the light", ("ON", "button-led")),
    ("turn on the light", ("ON", "button-led")),
    ("turn on the light", ("ON", "button-led")),
    ("turn on the light", ("ON", "button-led")),
    ("turn on the light", ("ON", "button-led")),
    ("turn on the light", ("ON", "button-led")),
    ("turn on the light", ("ON", "button-led")),
    ("turn on the light", ("ON", "button-led")),
    ("switch on light", ("ON", "button-led")),
    ("turn off the light", ("OFF", "button-led")),
    ("turn off the light", ("OFF", "button-led")),
    ("turn off the light", ("OFF", "button-led")),
    ("turn off the light", ("OFF", "button-led")),
    ("turn off the light", ("OFF", "button-led")),
    ("turn off the light", ("OFF", "button-led")),
    ("turn off the light", ("OFF", "button-led")),
    ("turn off the light", ("OFF", "button-led")),
    ("turn off the light", ("OFF", "button-led")),
    ("turn off led", ("OFF", "button-led")),
    ("turn off led", ("OFF", "button-led")),
    ("turn off led", ("OFF", "button-led")),
    ("turn off led", ("OFF", "button-led")),
    ("turn off led", ("OFF", "button-led")),
    ("turn off led", ("OFF", "button-led")),
    ("turn off led", ("OFF", "button-led")),
    ("turn off led", ("OFF", "button-led")),
    ("turn off led", ("OFF", "button-led")),
    ("switch the light off", ("OFF", "button-led")),

    # -------- DOOR --------
    ("mở cửa", ("ON", "button-door")),
    ("mở cửa", ("ON", "button-door")),
    ("mở cửa", ("ON", "button-door")),
    ("mở cửa", ("ON", "button-door")),
    ("mở cửa", ("ON", "button-door")),
    ("mở cửa", ("ON", "button-door")),
    ("mở cửa", ("ON", "button-door")),
    ("mở cửa", ("ON", "button-door")),
    ("mở cửa", ("ON", "button-door")),
    ("mở cửa", ("ON", "button-door")),
    ("mở cửa", ("ON", "button-door")),
    ("mở cửa", ("ON", "button-door")),
    ("mở cửa", ("ON", "button-door")),
    ("mở cửa", ("ON", "button-door")),
    ("mở cửa ra", ("ON", "button-door")),
    ("kéo cửa ra", ("ON", "button-door")),
    ("đẩy cửa ra", ("ON", "button-door")),
    ("đẩy cửa vô", ("ON", "button-door")),
    ("đóng cửa vô", ("OFF", "button-door")),
    ("đóng cửa vào", ("OFF", "button-door")),
    ("chặn cửa vào", ("OFF", "button-door")),
    ("chặn lối ra", ("OFF", "button-door")),
    ("chặn người lạ vào", ("OFF", "button-door")),
    ("chặn cửa", ("OFF", "button-door")),
    ("đóng cánh cửa", ("OFF", "button-door")),
    ("đóng cánh cửa", ("OFF", "button-door")),
    ("khép cửa", ("OFF", "button-door")),
    ("khép cửa", ("OFF", "button-door")),
    ("khóa cửa", ("OFF", "button-door")),
    ("khóa cửa", ("OFF", "button-door")),
    ("đóng cửa", ("OFF", "button-door")),
    ("đóng cửa", ("OFF", "button-door")),
    ("đóng cửa", ("OFF", "button-door")),
    ("đóng cửa", ("OFF", "button-door")),
    ("đóng cửa", ("OFF", "button-door")),
    ("đóng cửa", ("OFF", "button-door")),
    ("đóng cửa", ("OFF", "button-door")),
    ("đóng cửa", ("OFF", "button-door")),
    ("đóng cửa", ("OFF", "button-door")),
    ("đóng cửa", ("OFF", "button-door")),
    ("đóng cửa", ("OFF", "button-door")),
    ("đóng cửa", ("OFF", "button-door")),
    ("đóng cửa", ("OFF", "button-door")),
    ("đóng cửa", ("OFF", "button-door")),
    ("đóng cửa", ("OFF", "button-door")),
    ("đóng cửa", ("OFF", "button-door")),
    ("đóng cửa", ("OFF", "button-door")),
    ("đóng cửa", ("OFF", "button-door")),
    ("đóng cửa", ("OFF", "button-door")),
    ("đóng cửa", ("OFF", "button-door")),
    ("đóng cửa vào", ("OFF", "button-door")),
    ("bật cửa", ("ON", "button-door")),
    ("bật cửa", ("ON", "button-door")),
    ("tắt cửa", ("OFF", "button-door")),
    ("tắt cửa", ("OFF", "button-door")),
    ("open the door", ("ON", "button-door")),
    ("open the door", ("ON", "button-door")),
    ("open the door", ("ON", "button-door")),
    ("open the door", ("ON", "button-door")),
    ("open the door", ("ON", "button-door")),
    ("open the door", ("ON", "button-door")),
    ("open the door", ("ON", "button-door")),
    ("open the door", ("ON", "button-door")),
    ("open the door", ("ON", "button-door")),
    ("open the door", ("ON", "button-door")),
    ("open the door", ("ON", "button-door")),
    ("close the door", ("OFF", "button-door")),
    ("close the door", ("OFF", "button-door")),
    ("close the door", ("OFF", "button-door")),
    ("close the door", ("OFF", "button-door")),
    ("close the door", ("OFF", "button-door")),
    ("close the door", ("OFF", "button-door")),
    ("close the door", ("OFF", "button-door")),
    ("close the door", ("OFF", "button-door")),
    ("tiễn khách", ("OFF", "button-door")),
]

texts = [text for text, _ in data]
actions = [label[0] for _, label in data]
devices = [label[1] for _, label in data]

# Bước 2: Train 2 mô hình
action_model = Pipeline([
    ('tfidf', TfidfVectorizer()),
    ('clf', LogisticRegression())
])
action_model.fit(texts, actions)
joblib.dump(action_model, './action_model.joblib')

device_model = Pipeline([
    ('tfidf', TfidfVectorizer()),
    ('clf', LogisticRegression())
])
device_model.fit(texts, devices)
joblib.dump(device_model, './device_model.joblib')